<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <div class="glider-contain products-grid" style="max-width:1260px;margin-top:4rem;">
		<h2 class="text-center uutuudet"><span class="content"><?php echo __('Latest Products'); ?></span></h2>
        <ol class="glider-new-products products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="glider-item item product product-item">
                <div class="product-item-info" data-container="product-grid ?>">
                    <?php
                    $productImage = $block->getImage($_product, 'category_page_grid');
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
					
					<div class="secondary-addto-links actions-secondary" data-role="add-to-links">
						<a href="#"
						   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>'
						   class="action towishlist"
						   data-action="add-to-wishlist">
							<span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
						</a>
					</div>
					
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>
						<div class="product-price-cart">
							<?= /* @noEscape */ $block->getProductPrice($_product) ?>
							<?= $block->getProductDetailsHtml($_product) ?>

							<div class="product-item-inner">
								<div class="product actions product-item-actions">
									<div class="actions-primary">
										<?php if ($_product->isSaleable()):?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form"
												  data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
												  action="<?= $escaper->escapeUrl($postParams['action']) ?>"
												  method="post">
												<input type="hidden"
													   name="product"
													   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
												<input type="hidden"
													   name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
													   value="<?=
													   /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
														?>">
												<?= $block->getBlockHtml('formkey') ?>
												<button type="submit"
														title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
														class="action tocart primary"
														disabled>
													<span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
												</button>
											</form>
										<?php else:?>
											<?php if ($_product->isAvailable()):?>
												<div class="stock available">
													<span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
											<?php else:?>
												<div class="stock unavailable">
													<span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									
									<div data-role="add-to-links" class="actions-secondary">
										<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
											<?= $addToBlock->setProduct($_product)->getChildHtml() ?>
										<?php endif; ?>
									</div>
								</div>
							</div>
						</div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
		<button aria-label="Previous" class="glider-prev glider-new-products-prev"></button>
		<button aria-label="Next" class="glider-next glider-new-products-next"></button>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    window.addEventListener('load', function () {
		// Initialize Glider
		const myGliderNewProducts = new Glider(document.querySelector('.glider-new-products'), {
			slidesToShow: 2.2,
			slidesToScroll: 1,
			scrollLock: false,
			draggable: true,
			dots: false,
			rewind: true,
			duration: 0.6,
			dragVelocity: 1,
			scrollLockDelay: 100,
			arrows: {
				prev: '.glider-new-products-prev',
				next: '.glider-new-products-next'
			},
			responsive: [
				{
					breakpoint: 1200,
					settings: {
						slidesToShow: 5,
						slidesToScroll: 2
					}
				},
				{
					breakpoint: 991,
					settings: {
						slidesToShow: 4,
						slidesToScroll: 2
					}
				},
				{
					breakpoint: 768,
					settings: {
						slidesToShow: 3,
						slidesToScroll: 2
					}
				}
			]
		});
	});
</script>