<div class="single-images" style="padding-top: 14px;">
  <div class="top-container">
	<h2 class="text-center"><span class="content"><?php echo __('Popular Categories'); ?></span></h2>
	<div class="row">
	  <div class="col-md-3 col-xs-6" style="padding-left:15px;padding-right:15px;;padding-top:20px;">
		<a class="image-link" href="<?php echo $block->getCategoryUrlById(711); ?>">
		  <img src="<?php echo $block->getViewFileUrl('Mydreamday_Custom::images/popular_categories/easter-400.jpg') ?>" alt="<?php echo __('Easter Decorations'); ?>" width="255" height="255" />
		  <div class="feature-box-heading text-center">
			<span style="font-weight:500;"><?php echo __('Easter'); ?></span>
		  </div>
		</a>
	  </div>
	  <div class="col-md-3 col-xs-6" style="padding-left:15px;padding-right:15px;;padding-top:20px;">
		<a class="image-link" href="<?php echo $block->getCategoryUrlById(7); ?>">
		  <img src="<?php echo $block->getViewFileUrl('Mydreamday_Custom::images/popular_categories/leivonta-round-400x400.jpg') ?>" alt="<?php echo __('Baking Tools and Edible Cake Decorations'); ?>" width="255" height="255" />
		  <div class="feature-box-heading text-center">
			<span style="font-weight:500;"><?php echo __('Baking'); ?></span>
		  </div>
		</a>
	  </div>
	  <div class="col-md-3 col-xs-6" style="padding-left:15px;padding-right:15px;padding-top:20px;">
		<a class="image-link" href="<?php echo $block->getCategoryUrlById(3); ?>">
		  <img src="<?php echo $block->getViewFileUrl('Mydreamday_Custom::images/popular_categories/Haat-round-400x400.jpg') ?>" alt="<?php echo __('Hääteemat'); ?>" width="255" height="255" />
		  <div class="feature-box-heading text-center">
			<span style="font-weight:500;"><?php echo __('Wedding'); ?></span>
		  </div>
		</a>
	  </div>
	  <div class="col-md-3 col-xs-6" style="padding-left:15px;padding-right:15px;padding-top:20px;">
		<a class="image-link" href="<?php echo $block->getCategoryUrlById(658); ?>">
		  <img src="<?php echo $block->getViewFileUrl('Mydreamday_Custom::images/popular_categories/aikusten-juhlat-round-400x400.jpg') ?>" alt="<?php echo __('Adult Party Themes'); ?>" width="255" height="255" />
		  <div class="feature-box-heading text-center">
			<span style="font-weight:500;"><?php echo __('Adult Party'); ?></span>
		  </div>
		</a>
	  </div>
	  <div class="col-md-3 col-xs-6" style="padding-left:15px;padding-right:15px;padding-top:20px;">
		<a class="image-link" href="<?php echo $block->getCategoryUrlById(11); ?>">
		  <img src="<?php echo $block->getViewFileUrl('Mydreamday_Custom::images/popular_categories/Lastenjuhlat-round-400x400.jpg') ?>" alt="<?php echo __('Kids Party Themes'); ?>" width="255" height="255" />
		  <div class="feature-box-heading text-center">
			<span style="font-weight:500;"><?php echo __('Kids Parties'); ?></span>
		  </div>
		</a>
	  </div>
	  <div class="col-md-3 col-xs-6" style="padding-left:15px;padding-right:15px;padding-top:20px;">
		<a class="image-link" href="<?php echo $block->getCategoryUrlById(657); ?>">
		  <img src="<?php echo $block->getViewFileUrl('Mydreamday_Custom::images/popular_categories/1v-juhlat-round-400x400.jpg') ?>" alt="<?php echo __('Kids First Birthday Party Themes'); ?>" width="255" height="255" />
		  <div class="feature-box-heading text-center">
			<span style="font-weight:500;"><?php echo __('First Birthday'); ?></span>
		  </div>
		</a>
	  </div>
	  <div class="col-md-3 col-xs-6" style="padding-left:15px;padding-right:15px;padding-top:20px;">
		<a class="image-link" href="<?php echo $block->getCategoryUrlById(39); ?>">
		  <img src="<?php echo $block->getViewFileUrl('Mydreamday_Custom::images/popular_categories/baby-shower-round-400x400.jpg') ?>" alt="<?php echo __('Baby Shower Party Themes'); ?>" width="255" height="255" />
		  <div class="feature-box-heading text-center">
			<span style="font-weight:500;"><?php echo __('Baby Shower'); ?></span>
		  </div>
		</a>
	  </div>
	  <div class="col-md-3 col-xs-6" style="padding-left:15px;padding-right:15px;padding-top:20px;">
		<a class="image-link" href="<?php echo $block->getCategoryUrlById(26); ?>">
		  <img src="<?php echo $block->getViewFileUrl('Mydreamday_Custom::images/popular_categories/ristiaiset-round-400x400.jpg') ?>" alt="<?php echo __('Communion Party Themes'); ?>" width="255" height="255" />
		  <div class="feature-box-heading text-center">
			<span style="font-weight:500;"><?php echo __('Communion'); ?></span>
		  </div>
		</a>
	  </div>
	</div>
  </div>
</div>